### ISSUE TITLE
.txt files only match to .jpg files, not .JPG

### ISSUE THREAD

**Issue by agentmorris** [mfl28/BoundingBoxEditor#107]
When loading annotations for a folder, x.txt matches x.jpg, but not x.JPG.  In a perfect world, x.txt would also match x.jpeg, x.JPEG, x.png, x.bmp, etc., but in my scenario I would settle for x.JPG.

I work around this with symlinks, but that's not ideal.

Thanks!

**Comment by mfl28** [comment]
Hi! That's the next thing I'll update. There is no reason for this restriction to exist.
