### ISSUE TITLE
Hangs when using keyboard navigation in Linux

### ISSUE THREAD

**Issue by agentmorris** [mfl28/BoundingBoxEditor#66]
First, props on a fantastic tool; this is the fastest, most user-friendly tool I've come cross to load and preview YOLO-formatted annotations.

I am using Ubuntu 22.04, and I can load an image set, and navigate between images with the sidebar and the arrow keys, but when I hit "ctrl-a" or "ctrl-d" to switch between images, the image number indicator advances correctly, but I just get a permanent spinning wheel.

Nothing happens in the console when I hit the shortcut key; the only thing I see in the console is a warning from just after loading the images, which may or may not be relevant:

`(BoundingBoxEditor:2673766): Gdk-WARNING **: 16:44:00.036: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
`

"Hangs" may be a little misleading... the app is still responsive, the image just never loads, and clicking on other images (or the arrow keys) no longer loads images.

Thoughts?

Thanks!

**Comment by agentmorris** [comment]
Also, this feels related, so rather than filing a separate issue, just commenting here... I can ctrl-wheel to zoom in and out of an image, but when I ctrl-click to pan, the icon correctly changes to the little hand, but I can't actually pan the image.  This is all on Ubuntu 22.04.

**Comment by mfl28** [comment]
Hi @agentmorris! Sorry for the late response (for some reason I did not get a notification). Thanks for reporting this issue - I remember also sometimes getting this problem on Ubuntu. Will look into it when I find the time!

**Comment by mfl28** [comment]
* [x] Zooming and panning issue (resolved via #74).
* [ ] Images not loading issue after navigating on Linux (Could not yet reproduce with latest Bounding Box Editor version on Ubuntu 22.04).
