### ISSUE TITLE
Requires separate labels/images folders for loading YOLO annotation files

### ISSUE THREAD

**Issue by agentmorris** [mfl28/BoundingBoxEditor#67]
The YOLO format is admittedly a little... loose, but it's pretty typical to have a flat folder in which images and .txt files are side-by-side.  Bounding Box Editor appears to require separate folders for labels and images, or at least it strongly expects this.

I like it so much as a preview tool that I work around this by creating folders within my YOLO annotation folder, and filling one folder up with symlinks to all the images, and filling another folder up with symlinks to all the .txt files, but this seems like an extra hoop to jump through to use the standard format.

Any chance Bounding Box Editor could support typical YOLO folders, which look like:

image001.jpg
image001.txt
image002.jpg
image002.txt

Thanks!

**Comment by mfl28** [comment]
Yeah, I think it makes a lot of sense to add support for this case! Will look into it when I have time.
